name: clib-hello-world
version: 0.1.1
compiler:
  cc: gcc
  cflags: -Wall -Wextra -O2
  ldflags:
dependencies: {}  # No dependencies for this base library
test:
  cflags: -Wall -Wextra
platforms:
  linux:
    cflags: -fPIC
    ldflags: -shared
  darwin:
    cflags: -fPIC
    ldflags: -dynamiclib
  windows:
    cc: cl
    cflags: /W4
    ldflags: /DLL